"use strict";

const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const fonts = [
  {
    family: "VA Shantell Sans",
    weight: 400,
    file: "assets/fonts/ShantellSans-Regular.woff2"
  },
  {
    family: "VA LXGW WenKai Lite",
    weight: 300,
    file: "assets/fonts/LXGWWenKaiLite-Light-GB2312.woff2"
  }
];

const fontCss = fonts
  .map(({ family, weight, file }) => {
    const encoded = fs.readFileSync(path.join(root, file)).toString("base64");
    return `@font-face {\n  font-family: "${family}";\n  src: url("data:font/woff2;base64,${encoded}") format("woff2");\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n}`;
  })
  .join("\n\n");

const source = fs.readFileSync(path.join(root, "styles.source.css"), "utf8");
const banner = "/* Generated by scripts/build-styles.js. Edit styles.source.css, not this file. */";
fs.writeFileSync(path.join(root, "styles.css"), `${banner}\n${fontCss}\n\n${source}`);

console.log("Built self-contained styles.css with Shantell Sans and the LXGW WenKai Lite GB2312 subset.");
